name: Continuos Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Compose
        run: docker-compose -f docker-compose.yml up -d

      - name: Run Unit Tests
        run: dotnet test Wave.Commerce.Tests/Wave.Commerce.Tests.csproj

      - name: Run Integration Tests
        run: dotnet test Wave.Commerce.IntegrationTests/Wave.Commerce.IntegrationTests.csproj


  
